### ISSUE TITLE
[vue] vue cli 选择 dart-sass 后，使用 /deep/ 选择器报错的解决办法

### ISSUE THREAD

**Issue by Richard-Choooou** [Richard-Choooou/notes#10]
将 /deep/ 修改成 ::v-deep 
```css
::v-deep .el-header {
    padding: 0;
}
```
